/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import modelo.ConexionBd;
import modelo.Respuesta;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
/**
 *
 * @author Andrei
 */
public class FormularioRespuesta extends javax.swing.JFrame {
    private ConexionBd conexionBd;
    private Respuesta resp;
    private ButtonGroup opciones;
    /**
     * Creates new form FormularioRespuesta
     */
    public FormularioRespuesta(ConexionBd conexionBd) {
        this.conexionBd = conexionBd;
        initComponents();
        setFrame();
    }
    private void setFrame(){
        this.setLocationRelativeTo(null);
        this.setTitle("Formulario");
        opciones.add(this.jRadioButton1);
        opciones.add(this.jRadioButton2);
        opciones.add(this.jRadioButton3);
        this.setMinimumSize(new Dimension(500,250));
        this.setPreferredSize(new Dimension(500,250));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        PanelPregunta = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        PanelGuardar = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        Guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        PanelContenedor.setForeground(new java.awt.Color(255, 255, 255));
        PanelContenedor.setLayout(new java.awt.GridLayout(3, 0));

        PanelPregunta.setBackground(new java.awt.Color(255, 204, 204));
        PanelPregunta.setLayout(new javax.swing.BoxLayout(PanelPregunta, javax.swing.BoxLayout.LINE_AXIS));
        PanelPregunta.add(filler2);

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("¿Cuál es la capital de Francia?");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelPregunta.add(jLabel2);
        PanelPregunta.add(filler1);

        PanelContenedor.add(PanelPregunta);

        PanelGuardar.setBackground(new java.awt.Color(255, 255, 204));
        PanelGuardar.setLayout(new java.awt.BorderLayout());

        jRadioButton1.setText("Roma");
        jRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        PanelGuardar.add(jRadioButton1, java.awt.BorderLayout.CENTER);

        jRadioButton2.setText("Paris");
        jRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelGuardar.add(jRadioButton2, java.awt.BorderLayout.PAGE_START);

        jRadioButton3.setText("Berlin");
        jRadioButton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelGuardar.add(jRadioButton3, java.awt.BorderLayout.PAGE_END);

        PanelContenedor.add(PanelGuardar);

        Guardar.setText("Guardar Respuesta");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        PanelContenedor.add(Guardar);

        getContentPane().add(PanelContenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        String respuestaSeleccionada = "";
        boolean esCorrecta =false;
        
        if(jRadioButton1.isSelected()){
            respuestaSeleccionada = jRadioButton1.getText(); //paris
            esCorrecta = true;
        }else if(jRadioButton2.isSelected()){
            respuestaSeleccionada = jRadioButton2.getText();
            esCorrecta = false;
        }else if(jRadioButton3.isSelected()){
            respuestaSeleccionada = jRadioButton3.getText();
            esCorrecta = false;
        }
        if(respuestaSeleccionada.isEmpty()){
            JOptionPane.showMessageDialog(this,"Por favor elija una respuesta", "Advertencia",JOptionPane.WARNING_MESSAGE);
            
        }
        guardarRespuestaBD(respuestaSeleccionada, esCorrecta);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void guardarRespuestaBD(String respuesta, boolean esCorrecta){
        ConexionBd conexion = new ConexionBd();
        Connection conn = conexion.conectar();
        
        String sql = "INSERT INTO respuestas (texto, es_correcta) VALUES (?,?)";
        
        try{
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, respuesta);
            ps.setBoolean(2, esCorrecta);
            ps.executeUpdate();
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this,"Error al guardar la respuesta" + ex.getMessage());
        }finally{
            conexion.cerrar();
        }
        
    }
    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JPanel PanelGuardar;
    private javax.swing.JPanel PanelPregunta;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
