/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tema.pkg7;

import java.util.Arrays;
import java.util.Random;

/**
 *
 * @author Andrei
 */
public class Ejemplo1 extends javax.swing.JFrame {
    private int[] altura; //declaracion del array para almacenar las alturas, por defecto vale null
    /**
     * Creates new form Ejemplo1
     */
    public Ejemplo1() {
        initComponents();
        this.setTitle("Primer ejemplo array");
        this.setLocationRelativeTo(null);
                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldNumElementos = new javax.swing.JTextField();
        butonCrearArray = new javax.swing.JButton();
        butonMedia = new javax.swing.JButton();
        butonMinMax = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero elementos");

        textFieldNumElementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNumElementosActionPerformed(evt);
            }
        });

        butonCrearArray.setText("Crear un Array");
        butonCrearArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonCrearArrayActionPerformed(evt);
            }
        });

        butonMedia.setText("Altura media");
        butonMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonMediaActionPerformed(evt);
            }
        });

        butonMinMax.setText("Altura minima y maxima");
        butonMinMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonMinMaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(textFieldNumElementos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(butonCrearArray)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(butonMedia)
                .addGap(80, 80, 80)
                .addComponent(butonMinMax)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldNumElementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butonCrearArray))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butonMedia)
                    .addComponent(butonMinMax))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonCrearArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonCrearArrayActionPerformed
        if(this.textFieldNumElementos.getText().isEmpty()){
            //primero pillamos el texto luego vemos si tiene contenido con isEmpty
            System.out.println("Debes proporcionar un tamanio para el array");
        }
        //ha metido algo
        //comprobar si es valido --> debe ser --> numerico  y positivo
        try{
            int tamanio= Integer.parseInt(this.textFieldNumElementos.getText()); //creamos  el array de alturas
            if (tamanio <= 0){
                System.out.println("Error. El tamaño debe de ser positivo o distinto de 0.");
                return;
            }
            crearArray(tamanio);

        }catch(NumberFormatException ex){
            System.out.println("Debes de introducir un valor numerico");
        }
        
    }//GEN-LAST:event_butonCrearArrayActionPerformed

    private void textFieldNumElementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNumElementosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNumElementosActionPerformed

    private void butonMinMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonMinMaxActionPerformed
        // TODO add your handling code here:
        if (altura==null){ // si no se crea el array, altura = null, salta excepcion
            System.out.println("Primero crea el array");
            return;
        }
        alturaMinMax();
    }//GEN-LAST:event_butonMinMaxActionPerformed

    private void butonMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonMediaActionPerformed
        //calcular altura media  
        if (altura==null){
            System.out.println("Primero crea el array");
            return;
        }
        alturaMedia();
        
    }//GEN-LAST:event_butonMediaActionPerformed
    
    private void crearArray(int tamanio){
            altura = new int[tamanio];//dentro de los corchetes podemos poner 100 por ejemplo pero en este caso es variable porque l ointroduce el usuario.
            
            System.out.println("Array creado de tamanio " + altura.length);
        
            //Arrays.fill(altura, -1);
            //mostrarArray();
        
            rellenarArray();
            mostrarArray();
    }
    //muestra el contenido del array
    private void mostrarArray(){
        for(int i=0; i< altura.length; i++){
            System.out.println("Posicion: " + i + " " + altura[i]);
        }
        
    }
    private void rellenarArray(){
        //rellena el array con valores aleatorios entre 10 y 300
        Random r = new Random();
        for(int j=0;j <altura.length;j++){
            altura[j]=r.nextInt(10, 300);
        }
    }
    private void alturaMedia(){
        int suma =0;
        int cont=0;
        for(int i=0; i<altura.length;i++){
           if(altura[i] >=0){
               cont ++;
               suma += altura[i];
           }
        }
        System.out.println("Altura media: " + (double)suma/cont);
    }
    private void alturaMinMax(){
       int alturaMin=Integer.MAX_VALUE;
       int alturaMax=Integer.MIN_VALUE;
       for(int i=0; i < altura.length;i++){
           if(altura[i]<alturaMin){
               alturaMin=altura[i];
           }
           if(altura[i]<alturaMax){
               alturaMax=altura[i];
           }
       }
        System.out.printf("Altura minima %d %n", alturaMin);
        System.out.printf("Altura minima %d %n", alturaMax);
               
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejemplo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonCrearArray;
    private javax.swing.JButton butonMedia;
    private javax.swing.JButton butonMinMax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textFieldNumElementos;
    // End of variables declaration//GEN-END:variables
}
