/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import model.employees;
import model.csvReader;

/**
 *
 * @author Andrei
 */
public class employeesView extends javax.swing.JFrame {

    /**
     * Creates new form employeesView
     */
    public employeesView() {
        initComponents();
        setFrame();
    }
    public void setFrame(){
        this.setTitle("Empleados - HR");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lisataEmpleados = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        CargarDatos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(0, 2));

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        jPanel3.setMinimumSize(new java.awt.Dimension(502, 324));
        jPanel3.setPreferredSize(new java.awt.Dimension(502, 324));
        jPanel3.setLayout(new java.awt.BorderLayout(0, 2));

        jPanel1.setMinimumSize(new java.awt.Dimension(324, 78));
        jPanel1.setPreferredSize(new java.awt.Dimension(324, 78));
        jPanel1.setLayout(new java.awt.BorderLayout(2, 2));

        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));

        lisataEmpleados.setBorder(null);
        jScrollPane1.setViewportView(lisataEmpleados);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Ordenar por", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("ID");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton1);

        jRadioButton2.setText("Apellido");
        jPanel6.add(jRadioButton2);

        jRadioButton3.setText("Departamento");
        jPanel6.add(jRadioButton3);

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(100, 10, 120, 10));
        jPanel2.setMinimumSize(new java.awt.Dimension(178, 299));
        jPanel2.setPreferredSize(new java.awt.Dimension(178, 299));
        jPanel2.setLayout(new java.awt.GridLayout(3, 1, 5, 5));

        CargarDatos.setText("Cargar datos");
        CargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarDatosActionPerformed(evt);
            }
        });
        jPanel2.add(CargarDatos);

        jButton2.setText("Busqueda");
        jPanel2.add(jButton2);

        jButton3.setText("Añadir + datos");
        jPanel2.add(jButton3);

        jPanel3.add(jPanel2, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void CargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarDatosActionPerformed
        List<employees> empleados = csvReader.leerEmpleados();
        
        employees[] array = new employees[empleados.size()];
        array = empleados.toArray(array);
        
        String[] texto = new String[empleados.size()];
        for (int i =0; i<empleados.size(); i++){
            texto[i] = empleados.get(i).toString();
        }
        lisataEmpleados.setListData(texto);
    }//GEN-LAST:event_CargarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarDatos;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lisataEmpleados;
    // End of variables declaration//GEN-END:variables
}
